### ISSUE TITLE
make docs error in Ubuntu

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#144]
I've tried the command `make docs` from Mac and Ubuntu machines. This command works without any problem from the Mac machine, but I receive this error from the Ubuntu machine 

<img width="455" alt="image" src="https://github.com/langroid/langroid/assets/15859139/33c1a89c-800c-46b4-bd59-e4d02339bd75">

I tried to debug and strace the make process, removing this line `@pkill -f "mkdocs serve" 2>/dev/null || true` solves the problem.

**Comment by Mohannadcse** [comment]
@pchalasani. thank you for spotting out. 
I found these two ways that work for both Ubuntu and MacOS:
1. ```@-kill `ps aux | grep ".*mkdocs serve" | grep -v grep | awk '{print $2}'` 2>/dev/null || true```
2. ```@-kill `pgrep -f ".*mkdocs serve"` 2>/dev/null || true```

So now every time you run the command `make docs` or `make nodocs` the mkdocs will be killed, and restarted for the `make docs`

However, the problem with the second one is that there is a possibility `pgrep` isn't installed on the Mac machine. 

Please let me know which approach you prefer and if I need to create a new PR

**Comment by pchalasani** [comment]
Second solution is fragile. In any case,  it's not such a big deal... I wonder why doesn't `pkill ` work

**Comment by Mohannadcse** [comment]
Based on my understanding, when I run `pkill` command in the makefile directly from the terminal, the process isn't captured, the full path needs to be provided like this ```@pkill -f "/nobackup/langroid/.venv/bin/python /nobackup/langroid/.venv/bin/mkdocs serve" 2>/dev/null || true```, while when the command is executed from inside the Makefile, the make process gets killed because for some reason the mkdocs process is spawn through the make. 
`

**Comment by Mohannadcse** [comment]
I think solved
