### ISSUE TITLE
Solve logging issue in Colab

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#182]
**Is your feature request related to a problem? Please describe.**
Running agents from Google Colab is messy because the logging info is displayed in the terminal as well as the output together. As shown below.

<img width="1056" alt="image" src="https://github.com/langroid/langroid/assets/15859139/49fc05f3-f209-4157-ac1b-890c076cfa05">

**Describe the solution you'd like**
Can we create a flag to disable logging? Actually, by making the variable `tsv_logger ` a member variable, which can then be set to `None` when a task is created. Where I already tried to disable that like this `task.tsv_logger = None` but didn't work.

**Describe alternatives you've considered**
Any other option to disable logging?

**Comment by pchalasani** [comment]
I suspect you can solve this by setting `force_terminal=False` here:
https://github.com/langroid/langroid/blob/main/langroid/utils/logging.py#L128

**Comment by pchalasani** [comment]
Ignore this suggestion, it has nothing to do with this problem

**Comment by pchalasani** [comment]
We need to solve the following problem:

We are using `rich.console.Console` since it provides nice colored output in the log file. However when used in Colab, it writes to stdout instead of to the file.
The minimal example to get working is this -- 

```python
from rich.console import Console
with open("out.txt", "a") as f:
       console = Console(file=f, force_terminal=True, width=200)
       console.print("hello")
```
When you run this in a Colab cell, "hello" is printed to the output cell instead of being written to `out.txt`
Some tweak of this is needed, and once it works in Colab (without disturbing the logging we get when run in cmd line) we use it in `langroid/utils/logging.py`

**Comment by pchalasani** [comment]
If this is intractable, another solution is to have a global `agent_logs` setting (similar to `cache`, `streaming` etc)  that can be turned off in Colab notebooks, so it entirely suppresses logging. This way at least the output cells are not cluttered with these log outputs.

**Comment by Mohannadcse** [comment]
> We need to solve the following problem:
> 
> We are using `rich.console.Console` since it provides nice colored output in the log file. However when used in Colab, it writes to stdout instead of to the file. The minimal example to get working is this --
> 
> ```python
> from rich.console import Console
> with open("out.txt", "a") as f:
>     console = Console(file=f, force_terminal=True, width=200)
>     console.print("hello")
> ```
> 
> When you run this in a Colab cell, "hello" is printed to the output cell instead of being written to `out.txt` Some tweak of this is needed, and once it works in Colab (without disturbing the logging we get when run in cmd line) we use it in `langroid/utils/logging.py`

Let me try tweaking this

**Comment by Mohannadcse** [comment]
I think we can just add a flag to the agent/task to disable console. So when we run it from colab, we enable this flag. 

The above code works well without console stuff. 

```
with open("out.txt", "a") as f:
    print("hello", file=f)
```

**Comment by pchalasani** [comment]
rather than polluting the API of Agent/task, maybe have this as a global setting like `cache` etc... like `agent_logs`: if it is True, use console, else file

**Comment by pchalasani** [comment]
Actually, we could have a method `Task.agent_log(color=True)`, and when `color` is True, use Console else use file.
I think this is reasonable, what do you think?

**Comment by Mohannadcse** [comment]
This solution is more elegant to have this method `Task.agent_log(color=True)`

**Comment by Mohannadcse** [comment]
still hasn't solved the issue

<img width="1363" alt="image" src="https://github.com/langroid/langroid/assets/15859139/bbb899ae-b9a1-42e0-8c63-16ffc6a23242">

**Comment by Mohannadcse** [comment]
solved in PR https://github.com/langroid/langroid/pull/193
