### ISSUE TITLE
Error randomly occurs when a task executed more than one time in Colab

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#183]
**Describe the bug**
This error happens randomly after running the task. Seems LLM doesn't provide the required function/format for the tool that will be used. 
**To Reproduce**
This error happens when I run the same task more than one time. 

**Expected behavior**
Just wondering do we need to do validation, or if this is just an accepted behavior.

**Screenshots**
<img width="1218" alt="image" src="https://github.com/langroid/langroid/assets/15859139/8f527337-4f58-4906-ae59-e6d20d4ae939">

**Desktop (please complete the following information):**
From Google Colab

**Comment by pchalasani** [comment]
In general in any notebook, re-running a cell can have unpredictable effects. We can make sure that we splits in such a way that re-running them doesn't cause a problem

**Comment by pchalasani** [comment]
closing since this is not really a problem specific to Langroid.
