### ISSUE TITLE
Missing API key while using GoogleSearchTool

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#205]
**Describe the bug**
I receive this error when I try [GoogleSearchTool example] (https://github.com/langroid/langroid/blob/main/langroid/agent/stateless_tools/google_search_tool.py). 

```
2023-08-07 06:37:32 - WARNING - Encountered 403 Forbidden with reason "forbidden"
Agent: Error in tool/function-call web_search usage: <class 'googleapiclient.errors.HttpError'>: <HttpError 403 when requesting 
https://customsearch.googleapis.com/customsearch/v1?q=current+LLVM+version&num=5&alt=json returned "The request is missing a valid
API key.". Details: "[{'message': 'The request is missing a valid API key.', 'domain': 'global', 'reason': 'forbidden'}]">
```

**To Reproduce**
Run the above example `python3 examples/basic/chat-search.py`

**Expected behavior**
[GoogleSearchTool example] (https://github.com/langroid/langroid/blob/main/langroid/agent/stateless_tools/google_search_tool.py) expects some API keys. It's not clear where to get these keys from and no warning in advance about this need. So users know the problem isn't from the app itself.

**Screenshots**
<img width="1127" alt="image" src="https://github.com/langroid/langroid/assets/15859139/09c955ca-5674-4c84-b093-365b7c4e5d56">

**Comment by pchalasani** [comment]
Did you miss the instructions in the `README`, there are detailed instructions there. In any case, I also added a note in the script itself and in the corresponding test.
