### ISSUE TITLE
PyPi badge not showing latest version

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#224]
shows 0.1.51 but we are at 0.1.53

<img width="192" alt="image" src="https://github.com/langroid/langroid/assets/554347/a25b63a3-a63b-41f3-bf0b-52d4b8426ef5">

**Comment by Mohannadcse** [comment]
yes, noticed this issue, it doesn't sync immediately. I have been observing this behavior since the merge, and on my radar to fix it.

**Comment by Mohannadcse** [comment]
@pchalasani I'll close this after we bump the new version and make sure it updates successfully.

**Comment by Mohannadcse** [comment]
it took around 2 hrs to update
