### ISSUE TITLE
`num_tokens` reports different number of prompt tokens in contrast to OpenAI's Usage 

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#228]
**Describe the bug**
When `stream=True`, OpenAI doesn't report the number of prompt tokens, so we use the API `num_tokens` to calculate the number of these tokens. I noticed the number of prompt tokens computed (when`stream=True`) is different than the prompt tokens reported by OpenAI (when `stream=False`). This will ultimately affect the total cost.

**To Reproduce**
In the test case `test_token_usage.py`, the test case runs an agent based on these different stream options. If you enable `debug=True` at line 28. Then the number of `prompt tokens` and `completion tokens` will be printed out. 

**Expected behavior**
The number of tokens should be the same in case of `stream=True` and `stream=False`. Otherwise, the cost will be imprecise. 

**Screenshots**

<img width="295" alt="image" src="https://github.com/langroid/langroid/assets/15859139/b390ab50-b8d4-4630-a11e-695272016156">

<img width="303" alt="image" src="https://github.com/langroid/langroid/assets/15859139/a5885057-a434-4d0b-8e59-667b33b6c978">

**Comment by pchalasani** [comment]
can you run on a larger prompt and see whether the difference is a constant or it grows with the prompt size. If a constant, it could be that during handling of stream response, we are missing something at the beginning or end. Also if the diff is a constant , it's not a serious issue. If the true and computed costs are off by a slight constant amount, we should be fine.

**Comment by Mohannadcse** [comment]
Some trials here are based on the app `examples/docqa/chat_multi.py`

![image](https://github.com/langroid/langroid/assets/15859139/ea37849b-8878-47dc-9686-4d0b647219da)

<img width="468" alt="image" src="https://github.com/langroid/langroid/assets/15859139/f1c20501-8f38-4f67-b742-7ac08ee40b09">

**Comment by pchalasani** [comment]
It could be that the OpenAI API inserts some extra instructions/roles in the system prompt, so when it reports prompt tokens (in non-stream mode), it reports those. The diffs are not that significant, we can punt on this

**Comment by Mohannadcse** [comment]
I think we can close this now, but will keep an eye on it
