### ISSUE TITLE
Compute cost for Azure Openai

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#234]
Currently, we compute cost for Openai, but not Azure. However, in Azure, we don't know the chat mode e.g., gpt3.5 or gpt4. This causes a crashing problem. To solve this issue, there are two approaches that I'm currently aware of:
1. Add an env var that will ask the user to provide the chat model.
2. Extract automatically the chat model from the response. Specifically, by looking for the `model` key in the response Dict, which looks like this. 

```
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "model": "gpt-3.5-turbo-0613",
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}

```

I prefer the 2nd approach.

**Comment by pchalasani** [comment]
so azure does not allow explicit setting of chat model and therefore we don't know what it is until we get a response? I guess the chat model is configured when setting up the organization's Azure-OpenAI  subscription ? 
If so, then yes the approach 2 makes sense

**Comment by Mohannadcse** [comment]
Yes, you are right. The chat model is decided during the setup via Azure UI.

**Comment by Mohannadcse** [comment]
But when stream is true, the response object looks like this, which doesn't include the name of the chat model 


<img width="649" alt="image" src="https://github.com/langroid/langroid/assets/15859139/2f56f671-a628-4204-bc69-1786948eb56e">

**Comment by pchalasani** [comment]
ok then just require user to specify the exact model.
No need to make this more complex.

**Comment by Mohannadcse** [comment]
solved in PR https://github.com/langroid/langroid/pull/236
