### ISSUE TITLE
Prepend Tokens/ContextLength and cost in displayed LLM output

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#245]
It will be very useful to prepend this whenever we display an LLM output:

(1000+300/2048, $3)...

Which means:

Current response consumed 1000 input tokens, 300 output tokens, model context length = 2048, and cumulative cost so far is $3

**Comment by Mohannadcse** [comment]
Sure, let me work on it.

**Comment by Mohannadcse** [comment]
For context length, these are the APIs to get the context length `chat_context_length` and `completion_context_length`. Is there anything else I need to be aware of?

**Comment by Mohannadcse** [comment]
@pchalasani what do you think?

<img width="617" alt="image" src="https://github.com/langroid/langroid/assets/15859139/e25dbbb9-ec7c-43ad-a472-ee8e950252cf">

**Comment by pchalasani** [comment]
Nice

**Comment by Mohannadcse** [comment]
solved in PR https://github.com/langroid/langroid/pull/247
