### ISSUE TITLE
Length of prompt history becomes negative after being shortened 

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#250]
I'm using the spec-repair app (different version than the one on `langroid-apps`), and sometimes the history of messages becomes long. But when langroid tries to shorten it the length becomes negative, which causes OpenAI API to raise an error, as shown below.

```
2023-09-18 11:18:35 - WARNING - 
                    Chat Model context length is 8192 
                    tokens, but the current message history is 8197 tokens long.
                    Dropped the 1 messages
                    from early in the conversation history so total tokens are 
                    low enough to allow minimum output length of 
                    64 tokens.
                    
2023-09-18 11:18:35 - WARNING - 
                Tried to shorten prompt history for chat mode 
                but the feasible output length -5 is still
                less than the minimum output length 64.
                Your chat history is too long for this model, 
                and the response may be truncated.
                
2023-09-18 11:18:35 - ERROR - OpenAI API request failed with error: -5 is less than the minimum of 1 - 'max_tokens'.
2023-09-18 11:18:35 - ERROR - OpenAI API error: -5 is less than the minimum of 1 - 'max_tokens'
```

I think Langroid should try gradually and iteratively to remove messages from the message history.

**Comment by pchalasani** [comment]
> Langroid should try gradually and iteratively to remove messages

This is exactly what it is already doing, and despite dropping all removable messages, the history is longer than model's context length (which implies feasible output len = ModelContextLen - HistLen < 0). It's not really a bug, but I'll catch the negative output len and throw a useful/informative err msg.

**Comment by Mohannadcse** [comment]
Agreed, not a bug. To handle this, I just removed all history messages except the 1st two messages (system and user), but I keep track of minimal info that I provide as a pending message to LLM to answer.

**Comment by pchalasani** [comment]
I made some changes in `chat_agent` so that all instruction-type text will be in the system msg, so now the first user message should be removable. So in `chat_agent` I'm changing this part of the code to preserve the sys msg and last msg, repeatedly drop the first msg after the sys msg.

**Comment by Mohannadcse** [comment]
@pchalasani did your recent PR solve this issue?
