### ISSUE TITLE
Error while constructing the tool inside `json_format_rules`

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#259]
I received the following error while running my `repair_spec` app (the modified version) BUT after updating to Langroid `0.1.81`. 
```
ErrorWrapper(exc=MissingError(), loc=('fix',))
```
Here is a screenshot from the debugger 

<img width="650" alt="image" src="https://github.com/langroid/langroid/assets/15859139/5de82a91-da62-42fa-87a2-fd06cf0ffcd5">

The schema looks has been constructed correctly 

<img width="645" alt="image" src="https://github.com/langroid/langroid/assets/15859139/e7f7a0b0-e6b4-41c9-8967-cb24e31e8a46">

Specifically, the error happened inside this logic in the file `chat_agent.py`

```
json_instructions = "\n\n".join(
            [
                textwrap.dedent(
                    f"""
                TOOL: {msg_cls.default_value("request")}
                PURPOSE: {msg_cls.default_value("purpose")} 
                JSON FORMAT: {
                    json.dumps(
                        msg_cls.llm_function_schema(request=True).parameters,
                        indent=4,
                    )
                }
                {"EXAMPLE: " + msg_cls.usage_example() if msg_cls.examples() else ""}
                """.lstrip()
                )
                for i, msg_cls in enumerate(enabled_classes)
                if msg_cls.default_value("request") in self.llm_tools_usable
            ]
```

specifically, at this line ` {"EXAMPLE: " + msg_cls.usage_example() if msg_cls.examples() else ""}
     """.lstrip()`

**Comment by pchalasani** [comment]
the most important part you left out is, what was your pydantic tool definition? The err is clearly saying that the example is missing one of the fields that is defined as required (i.e. does not have a default) in the Tool definition

**Comment by Mohannadcse** [comment]
solved
