### ISSUE TITLE
Support for Anthropic Claude

### ISSUE THREAD

**Issue by ranjancse26** [langroid/langroid#276]
**Is your feature request related to a problem? Please describe.**
Requesting the Anthropic Claude support for handling 100k context window

**Describe the solution you'd like**
Suggestion to extend the model to support for Anthropic Claude based models.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pchalasani** [comment]
@ranjancse26 this is already supported in Langroid. In fact you can use Langroid with over a 100 LLM providers via the excellent [LiteLLM](https://github.com/BerriAI/litellm) library. See the guide here https://langroid.github.io/langroid/tutorials/non-openai-llms/

Let me know if you run into issues.

**Comment by ranjancse26** [comment]
Oh I see. That's great, a ton of folks are already using [LiteLLM](https://github.com/BerriAI/litellm) library
