### ISSUE TITLE
Add Metaphor search similar to `GoogleSearchTool`

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#316]
Metaphor search API docs -- https://platform.metaphor.systems/

The implementation should be similar to [`GoogleSearchTool`](https://github.com/langroid/langroid/blob/main/langroid/agent/tools/google_search_tool.py)

**Comment by pchalasani** [comment]
Once this is done, add to this `chat-search.py` script as one of the search options:
https://github.com/langroid/langroid/blob/main/examples/basic/chat-search.py

**Comment by Alfr3doK1ng** [comment]
On it

**Comment by pchalasani** [comment]
implemented by #376
