### ISSUE TITLE
Local LLM via server without OpenAI API key

### ISSUE THREAD

**Issue by unoriginalscreenname** [langroid/langroid#336]
Your documentation says that you can set a local url to serve the language model via something like oobabooga.  However, it's not clear how to do this without putting in your OpenAI API key.  It throws an error saying you need the API key.  Then, when you do add your API key, it continues to throw an error:

openai.BadRequestError: Error code: 400 - {'error': {'message': 'invalid model ID', 'type': 'invalid_request_error', 'param': None, 'code': None}}

This library looks promising, but it would be really great to clarify if local LLM is available or not.  The documentation isn't exactly clear.  Could you help clarify?

**Comment by pchalasani** [comment]
@unoriginalscreenname Yes you definitely can use Langroid with practically any LLM, local or remote, via LiteLLM for most scenarios. Here's a short example script in this branch (awaiting PR merge):
https://github.com/langroid/langroid/blob/042ce4544d5fd689a7aa1ce9f5c1c004f18af9d6/examples/basic/chat-local.py

Full docs on non-OpenAI LLMs:
https://langroid.github.io/langroid/tutorials/non-openai-llms/

**Comment by TheBitmonkey** [comment]
I am getting the same error here too. 

The answer provided is missing the point. Langroid should not be making any call to openai when being used in local mode. Seems to be an issue with the setup.
