### ISSUE TITLE
Logging issue: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by benceblaske** [langroid/langroid#341]
**Describe the bug**
Seems that the tsv_logger code does not work well on Windows 11: if the log files already exists (second execution of the same script), it cannot remove the previously saved files:

```
\logging.p │
│ y:77 in setup_file_logger                                                                        │
│                                                                                                  │
│    74 │   os.makedirs(os.path.dirname(filename), exist_ok=True)                                  │
│    75 │   if not append:                                                                         │
│    76 │   │   if os.path.exists(filename):                                                       │
│ ❱  77 │   │   │   os.remove(filename)                                                            │
│    78 │                                                                                          │
│    79 │   logger = setup_logger(name)                                                            │
│    80 │   handler = logging.FileHandler(filename)   
```

I have read a lot of SO and reddit posts about such errors, and it seems it's related to how Windows handles files. I tried also running VS Code with elevated admin rights, but the same error occurs.

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process`

**To Reproduce**

Run any agent based example, e.g. examples/docqa/chat.py on Windows 11 (using venv, but I suppose without venv it would also occur).

**Expected behavior**
No error. :)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Using VS Code, with Python venv.

**Comment by TheBitmonkey** [comment]
I can confirm this is happening on Windows 10 with the same setup. Did you solve this @benceblaske?

**Comment by pchalasani** [comment]
I don’t have a windows computer to test this, but if you have a simple workaround or fix, I’m happy to implement it. One thing might be to use a context manager when writing to the log files so they are closed properly.

**Comment by Mohannadcse** [comment]
Langroid Docker image is available, just follow these instructions https://github.com/langroid/langroid?tab=readme-ov-file#whale-docker-instructions. This might be an alternative solution.

**Comment by pchalasani** [comment]
@benceblaske @TheBitmonkey PR #348 should hopefully fix this -- I avoid deleting the file, but instead open it in "w" mode, which would effectively clear out the contents without deleting it.

**Comment by pchalasani** [comment]
@benceblaske and @TheBitmonkey  please install 0.1.159 and let me know if it's not fixed.

**Comment by benceblaske** [comment]
> @benceblaske and @TheBitmonkey please install 0.1.159 and let me know if it's not fixed.

I have tested it with 0.1.160 and can confirm that it works perfectly now! :) Thanks a lot for your quick fix!
