### ISSUE TITLE
Local Embedding Issues

### ISSUE THREAD

**Issue by TheBitmonkey** [langroid/langroid#351]
Hi, super module good sir. 

I am having some difficulties trying to get embedding working on my end (could be user error). Earlier I was using LM Studio but that does not have an embedding endpoint. I have it running now with Ollama through litellm as it was before. But embedding is still not working I believe. 

When I look at the class OpenAIEmbeddingsConfig in the embedding models folder I can not see any reference to api-base var, it seems to presume the use of the openai api directly. I think that is where my issue is and I can't seem to get a work around to function on my end. Any help would be appreciated. Cheers.

**Comment by pchalasani** [comment]
> get embedding working on my end

Can you elaborate? Are you trying to use embedding models from Huggingface? or via Ollama (if so, I wasn't aware this is possible)

**Comment by TheBitmonkey** [comment]
I am just finding out that ollama used to do it but now doesn't https://github.com/jmorganca/ollama/issues/834 this is where my confusion came from.

**Comment by TheBitmonkey** [comment]
I think I was wrong entirely... I see you have the same sentence transformer model integrated with langroid (cool), I think that worked actually. 

What happens to me is that the chat-multi-extract seems to extract the doc. create the vector store etc but actually only reads the example data at the end. I am trying this all locally so it could be my model setup and vars, etc.

**Comment by pchalasani** [comment]
> only reads the example data at the end.

Didn't understand what you meant by this

**Comment by pchalasani** [comment]
@TheBitmonkey closing this, let me know if we need to revisit.
