### ISSUE TITLE
The cmd "pip install langroid[hf-embeddings]" does not work 

### ISSUE THREAD

**Issue by mturk24** [langroid/langroid#360]
**Describe the bug**
I am using Python 3.11.5 and am able to run 

`pip install langroid`

just fine. However when running:

`pip install langroid[hf-embeddings]`

I get the following error:

`zsh: no matches found: langroid[hf-embeddings]`

I took these cmds directly from the README

**To Reproduce**
Run the cmd

**Expected behavior**
The version of langroid compatible with Hugging Face embeddings should install properly

**Screenshots**

**Desktop (please complete the following information):**

OS is macOS Sonoma 14.1.2 and browser is chrome

**Additional context**

**Comment by Mohannadcse** [comment]
Thanks for submitting this issue. 
Since you are using zsh, can you try the command as follows `pip install langroid\[hf-embeddings\]` or `pip install 'langroid[hf-embeddings]'`?

**Comment by mturk24** [comment]
Thanks `pip install langroid\[hf-embeddings\]` actually worked! Can you update the README now to reflect this for zsh users? Or I can put in a pull request

**Comment by Mohannadcse** [comment]
please go ahead and make a PR.
Thanks for your help

**Comment by mturk24** [comment]
No problem! Made the PR: https://github.com/langroid/langroid/pull/361

**Comment by pchalasani** [comment]
> Thanks `pip install langroid\[hf-embeddings\]` actually worked! Can you update the README now to reflect this for zsh users? Or I can put in a pull request

This is a common zsh issue. I put “langroid[hf-embeddings]” inside quotes to get it to work. But I agree it’s worth adding this tip.
