### ISSUE TITLE
Follow-up question support

### ISSUE THREAD

**Issue by Gusakovskyi** [langroid/langroid#398]
**Is your feature request related to a problem? Please describe.**
I am building a RAG chat bot for restaurant busines.
Bot helps clients with menu, prices, orders, etc.
I am using embeddings for menu items and have problem to answer the follow-up questions, like:

Q: Do you have some pasta?
A: Yes, we have Carbonara pasta
Q: Is it spicy?

Searching over the vector store in this case executed without any knowledge about Carbonara pizza so response will be unexpected.

Do you have some tools to implement a correct behavior?

**Comment by pchalasani** [comment]
Are you using DocChatAgent? It should be able to rephrase the follow up question into a stand alone question. If you can share your script or a small example, that will help us guide you.
