### ISSUE TITLE
ModuleNotFoundError: No module named 'langroid.agent'; 'langroid' is not a package

### ISSUE THREAD

**Issue by SaumyaDabhi** [langroid/langroid#406]
I am currently running the following script and getting the error of langroid not found even though I installed it using "pip install langroid". I ran the script in three different python environments 3.10,3.11 and 3.12 but the error persists.

Here is the code:
"""
2-agent doc-chat:
WriterAgent is in charge of answering user's question.
Breaks it down into smaller questions (if needed) to send to DocAgent,
who has access to the docs via a vector-db.

Run like this:
python3 examples/docqa/doc-chat-2.py

"""
import typer
from rich import print
import os

from langroid.agent.special.doc_chat_agent import (
    DocChatAgent,
    DocChatAgentConfig,
)
from langroid.mytypes import Entity
from langroid.parsing.parser import ParsingConfig, PdfParsingConfig, Splitter
from langroid.agent.chat_agent import ChatAgent, ChatAgentConfig
from langroid.agent.task import Task
from langroid.language_models.openai_gpt import OpenAIGPTConfig
from langroid.agent.tools.recipient_tool import RecipientTool
from langroid.utils.configuration import set_global, Settings
from langroid.utils.logging import setup_colored_logging
from langroid.utils.constants import NO_ANSWER

app = typer.Typer()

setup_colored_logging()
os.environ["TOKENIZERS_PARALLELISM"] = "false"

def chat(config: DocChatAgentConfig) -> None:
    doc_agent = DocChatAgent(config)
    print("[blue]Welcome to the document chatbot!")
    doc_agent.user_docs_ingest_dialog()
    print("[cyan]Enter x or q to quit, or ? for evidence")
    doc_task = Task(
        doc_agent,
        interactive=False,
        name="DocAgent",
        done_if_no_response=[Entity.LLM],  # done if null response from LLM
        done_if_response=[Entity.LLM],  # done if non-null response from LLM
    )

    writer_agent = ChatAgent(
        ChatAgentConfig(
            name="WriterAgent",
            llm=OpenAIGPTConfig(),
            vecdb=None,
        )
    )
    writer_agent.enable_message(RecipientTool)
    writer_task = Task(
        writer_agent,
        name="WriterAgent",
        interactive=True,
        system_message=f"""
        You are tenacious, creative and resourceful when given a question to 
        find an answer for. You will receive questions from a user, which you will 
        try to answer ONLY based on content from certain documents (not from your 
        general knowledge). However you do NOT have access to the documents. 
        You will be assisted by DocAgent, who DOES have access to the documents.

        Here are the rules:
        (a) when the question is complex or has multiple parts, break it into small 
         parts and/or steps and send them to DocAgent
        (b) if DocAgent says {NO_ANSWER} or gives no answer, try asking in other ways.
        (c) Once you collect all parts of the answer, say "ANSWER:" and 
            show me the consolidated final answer. 
        (d) DocAgent has no memory of previous dialog, so you must ensure your 
            questions are stand-alone questions that don't refer to entities mentioned 
            earlier in the dialog.
        (e) if DocAgent is unable to answer after your best efforts, you can say
            {NO_ANSWER} and move on to the next question.
        (f) answers should be based ONLY on the documents, NOT on your prior knowledge.
        (g) be direct and concise, do not waste words being polite.
        (h) if you need more info from the user, before asking DocAgent, you should 
        address questions to the "User" (not to DocAgent) to get further 
        clarifications or information. 
        (i) Always ask questions ONE BY ONE (to either User or DocAgent), NEVER 
            send Multiple questions in one message.
        (j) Use bullet-point format when presenting multiple pieces of info.
        (k) When DocAgent responds without citing a SOURCE and EXTRACT(S), you should
            send your question again to DocChat, reminding it to cite the source and
            extract(s).

        Start by asking the user what they want to know.
        """,
    )
    writer_task.add_sub_task(doc_task)
    writer_task.run()

@app.command()
def main(
        debug: bool = typer.Option(False, "--debug", "-d", help="debug mode"),
        nocache: bool = typer.Option(False, "--nocache", "-nc", help="don't use cache"),
        cache_type: str = typer.Option(
            "redis", "--cachetype", "-ct", help="redis or momento"
        ),
) -> None:
    config = DocChatAgentConfig(
        n_query_rephrases=0,
        cross_encoder_reranking_model="cross-encoder/ms-marco-MiniLM-L-6-v2",
        hypothetical_answer=False,
        assistant_mode=True,
        n_neighbor_chunks=2,
        parsing=ParsingConfig(  # modify as needed
            splitter=Splitter.TOKENS,
            chunk_size=100,  # aim for this many tokens per chunk
            n_neighbor_ids=5,
            overlap=20,  # overlap between chunks
            max_chunks=10_000,
            # aim to have at least this many chars per chunk when
            # truncating due to punctuation
            min_chunk_chars=200,
            discard_chunk_chars=5,  # discard chunks with fewer than this many chars
            n_similar_docs=5,
            # NOTE: PDF parsing is extremely challenging, each library has its own
            # strengths and weaknesses. Try one that works for your use case.
            pdf=PdfParsingConfig(
                # alternatives: "haystack", "unstructured", "pdfplumber", "fitz"
                library="pdfplumber",
            ),
        ),
    )

    set_global(
        Settings(
            debug=debug,
            cache=not nocache,
            cache_type=cache_type,
        )
    )
    chat(config)

if __name__ == "__main__":
    app()

And here is the error:
Traceback (most recent call last):
  File "C:\Users\saumy\Downloads\ChatBot\langroid.py", line 15, in <module>
    from langroid.agent.special.doc_chat_agent import (
  File "C:\Users\saumy\Downloads\ChatBot\langroid.py", line 15, in <module>
    from langroid.agent.special.doc_chat_agent import (
ModuleNotFoundError: No module named 'langroid.agent'; 'langroid' is not a package

**Comment by pchalasani** [comment]
This looks like `langroid` is not being recognized at all in your environment.

Please following the exact install instructions in the README of the `langroid-examples` repo: https://github.com/langroid/langroid-examples

If it still doesn't work, let me know the exact steps you took to install langroid.

**Comment by SaumyaDabhi** [comment]
I followed the instructions and the script in the examples folder runs fine, but when I make another file let's say "lagroid.py" and copy the content of script "doc-chat-2.py" into that and run it then am getting the modulenotfound error. why is that?

**Comment by SaumyaDabhi** [comment]
Thank you for your help. Apparently, now I am facing a connection error to OpenAI. I am running the following script:
# (1) Get the lease document

import requests
file_url = "https://raw.githubusercontent.com/langroid/langroid-examples/main/examples/docqa/lease.txt"
response = requests.get(file_url)
with open('lease.txt', 'wb') as file:
    file.write(response.content)

# verify
#with open('lease.txt', 'r') as file:
#   print(file.read())

from langroid.agent.special import DocChatAgent, DocChatAgentConfig
from langroid.vector_store.lancedb import LanceDBConfig
from langroid.embedding_models.models import OpenAIEmbeddingsConfig
from langroid.embedding_models.models import SentenceTransformerEmbeddingsConfig
from langroid.parsing.parser import ParsingConfig

oai_embed_config = OpenAIEmbeddingsConfig(
    model_type="openai",
    model_name="text-embedding-ada-002",
    dims=1536,
)

# (2) Configure DocChatAgent

cfg = DocChatAgentConfig(
    name="RAG",
    parsing=ParsingConfig(
        chunk_size=100,
        overlap=20,
        n_similar_docs=4,
    ),
    show_stats=False,
    cross_encoder_reranking_model="",
    llm=llm_cfg,
    vecdb=LanceDBConfig(
        embedding=oai_embed_config,
        collection_name="lease",
        replace_collection=True,
    ),
    doc_paths=["lease.txt"]
)

# (3) Create DocChatAgent, interact with it
rag_agent = DocChatAgent(cfg)
response = rag_agent.llm_response("What is the start date of the lease?")
assert "2013" in response.content

And the error I got is this and keeps going on:

WARNING:langroid.language_models.utils:OpenAI API request failed with errorConnection error.. 
                    Retrying in 111.01054350577557 seconds...
2024-02-21 16:32:21 - WARNING - OpenAI API request failed with errorConnection error.. 
                    Retrying in 111.01054350577557 seconds...
WARNING:langroid.language_models.utils:OpenAI API request failed with errorConnection error.. 
                    Retrying in 266.38226142682373 seconds...
2024-02-21 16:34:15 - WARNING - OpenAI API request failed with errorConnection error.. 
                    Retrying in 266.38226142682373 seconds...
WARNING:langroid.language_models.utils:OpenAI API request failed with errorConnection error.. 
                    Retrying in 561.3158388183265 seconds...
2024-02-21 16:38:45 - WARNING - OpenAI API request failed with errorConnection error.. 
                    Retrying in 561.3158388183265 seconds...

I have enough balance in my openai account and generated new keys but it does not seem to work and stuck at making connection.

**Comment by pchalasani** [comment]
Before trying this example, can you run this and see if it works:

```
import langroid as lr
import langroid.language_models as lm

llm_config = lm.OpenAIGPTConfig()
agent_config = lr.ChatAgentConfig(
    llm=llm_config,
    system_message="You are a helpful assistant, help me with some questions"
)

agent = lr.ChatAgent(agent_config)
task = lr.Task(agent, interactive=True)

task.run()
```

**Comment by SaumyaDabhi** [comment]
This works!

**Comment by SaumyaDabhi** [comment]
Tried it, and the connection error persists.

**Comment by SaumyaDabhi** [comment]
Hello,
With the recent March 2024 updates, The code I have been running is throwing me this error: 

TypeError                                 Traceback (most recent call last)
[<ipython-input-16-de5fd049e86b>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from langroid.language_models.openai_gpt import (
      2     OpenAIChatModel, OpenAIGPT, OpenAIGPTConfig
      3 )

7 frames
[/usr/lib/python3.10/typing.py](https://localhost:8080/#) in _type_check(arg, msg, is_argument, module, allow_special_forms)
    174         return arg
    175     if not callable(arg):
--> 176         raise TypeError(f"{msg} Got {arg!r:.100}.")
    177     return arg
    178 

TypeError: Tuple[t0, t1, ...]: each t must be a type. Got <module 'PIL.Image' from '/usr/local/lib/python3.10/dist-packages/PIL/Image.py'>.


The following is the code I am using:

from langroid.language_models.openai_gpt import (
    OpenAIChatModel, OpenAIGPT, OpenAIGPTConfig
)

It was working fine before, but after the recent updates, it is not.

**Comment by pchalasani** [comment]
Your error trace shows `python3.10`. Langroid requires 3.11 as it says in the README.
