### ISSUE TITLE
Pydantic import Basemodel throws import error in examples

### ISSUE THREAD

**Issue by Code-is-hope** [langroid/langroid#427]
**Describe the bug**
repo_loader.py", line 19, in <module> from pydantic import BaseModel, BaseSettings, Field ->
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package.
* - Many of the logic leveraging pydantic seems to be affected
**To Reproduce**

chainlit run examples/chainlit/simplest.py (any of the examples it seems)

**Expected behavior**
Normal operation

**Desktop (please complete the following information):**
 Windows 11

**Additional context**
An mass update on all  the files and replace pydantic with pydantic_settings (from pydantic_settings import Basemodel)

**Comment by pchalasani** [comment]
> BaseSettings has been moved to the pydantic-settings

This shouldn't be happening if you either installed langroid from pip or followed the local env set up instructions in the langroid main README. The above error indicates you may be using pydantic v2.
Langroid uses v1.

**Comment by Code-is-hope** [comment]
A RTFM moment. :-)

Thx for your fast response and I can confirm that this was my issue.
