### ISSUE TITLE
`ImagePdfParser` module causes Langroid import error

### ISSUE THREAD

**Issue by nathnx** [langroid/langroid#440]
**Describe the bug**
An error raised when importing langroid library. It is because the module `Image` from `PIL` package has been import incorrectly.

**To Reproduce**
1. `import langroid as lr`
2. See the error

**Expected behavior**
The error `TypeError: Tuple[t0, t1, ...]: each t must be a type. Got <module 'PIL.Image' from ....`

**Desktop:**
 - Chip: Apple M2
 - OS: macOS
 - Version: 14.2.1 (23C71)
 - Langroid: 0.1.222
 - Python: 3.10.14

**Comment by pchalasani** [comment]
This is because you’re using Python 3.10.
Langroid requires 3.11 as it says in the README

**Comment by mdelmans** [comment]
@pchalasani is there a reason why it is

```py
python = ">=3.9.1,<3.12"
```

in `pyproject.toml` ?

Fell in the same trap as @nathnx as poetry did not complain during the installation.

**Comment by pchalasani** [comment]
@mdelmans no reason; it’s an oversight, I’ll update
