### ISSUE TITLE
How do I use langroid to call a public API?

### ISSUE THREAD

**Issue by yhfwww** [langroid/langroid#446]
How do I use langroid to call a public API?

**Comment by pchalasani** [comment]
can you elaborate?

**Comment by yhfwww** [comment]
Just like the ability of langchain's APIChain to interface with GET or POST type REST APIs, can langroid do that?

**Comment by pchalasani** [comment]
Sure, you would define a `ToolMessage` to call the API. See this example of a tool for DuckDuckGo search: https://github.com/langroid/langroid/blob/main/langroid/agent/tools/duckduckgo_search_tool.py

And example script using this tool https://github.com/langroid/langroid/blob/main/examples/basic/chat-search.py

Read more about tools here: https://langroid.github.io/langroid/quick-start/chat-agent-tool/
