### ISSUE TITLE
'langroid' is not a package

### ISSUE THREAD

**Issue by AtmehEsraa** [langroid/langroid#457]
**Describe the bug**
I try to import 
import langroid as lr
import langroid.language_models  as lm
from langroid.agent.special.doc_chat_agent import DocChatAgent, DocChatAgentConfig

but it give me :
ModuleNotFoundError: No module named 'langroid.language_models'; 'langroid' is not a package

**Comment by pchalasani** [comment]
This looks like an environment issue. It shouldn’t be happening if Langroid is installed as in the instructions in a fresh virtual env, etc.

**Comment by AtmehEsraa** [comment]
What should be the solution?

**Comment by AtmehEsraa** [comment]
> This looks like an environment issue. It shouldn’t be happening if Langroid is installed as in the instructions in a fresh virtual env, etc.

What should be the solution

**Comment by pchalasani** [comment]
Hard to say without knowing more details on the exact steps you have done.

**Comment by AtmehEsraa** [comment]
> Hard to say without knowing more details on the exact steps you have done.

I just utilized virtualenv with python 11.8 and run pip install langroid

**Comment by AtmehEsraa** [comment]
@pchalasani

**Comment by pchalasani** [comment]
I can't reproduce this error, nor have I heard anyone else report this. Just for reference, the following should work. Make sure you have python >= 3.11, and best to work in a fresh virtual environment, using `venv`. I have not tested with other tools like `virtualenv` or `conda` etc

```
python3 -m venv .venv
. ./.venv/bin/activate
pip install langroid
```
To install and set python versions, use `pyenv`:
```
pyenv install 3.11.0
pyenv global 3.11.0
```
