### ISSUE TITLE
Error : each t must be a type. Got <module 'PIL.Image'

### ISSUE THREAD

**Issue by hassanInfo** [langroid/langroid#460]
Hi everyone,

I'm encountering a TypeError when using the langroid library for document parsing. 
when i do :

**import langroid as lr**

i got the error Message:

**TypeError: Tuple[t0, t1, ...]: each t must be a type. Got <module 'PIL.Image' from '..../venv/lib/python3.10/site-packages/PIL/Image.py'>**

hopefully get some help from the community.

**Comment by Mohannadcse** [comment]
Seems you are using python 3.10, Langroid requires Python 3.11+

**Comment by hassanInfo** [comment]
Thank you @Mohannadcse.
