### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by torntrousers** [langroid/langroid#495]
Hello. In your top level readme in the section[Set up environment variables (API keys, etc)](https://github.com/langroid/langroid?tab=readme-ov-file#set-up-environment-variables-api-keys-etc) the "[this OpenAI Page](https://help.openai.com/en/collections/3675940-getting-started-with-openai-api)" link gives a this page doesn't exist error.

**Comment by pchalasani** [comment]
Thanks @torntrousers fixed it
