### ISSUE TITLE
Issue in demo example - Capital tool is not invoked 

### ISSUE THREAD

**Issue by InfantJerin** [langroid/langroid#568]
with reference to this example 
https://github.com/langroid/langroid/blob/01832b823071191584aea6cccc9ebd06b11d3962/examples/chainlit/chat-tool.py#L47

I'm using google vertexAI and gemini pro model 

llm_cfg = lm.OpenAIGPTConfig( # or OpenAIAssistant to use Assistant API 
  # any model served via an OpenAI-compatible API
  chat_model='litellm/gemini-1.5-pro', # or, e.g., "ollama/mistral"
)

os.environ['GOOGLE_CLOUD_PROJECT'] = 
os.environ['VERTEXAI_PROJECT'] = 
os.environ['VERTEXAI_LOCATION'] = 
os.environ['PYTHONIOENCODING'] =

I'm getting the following error - 

2024-09-23 00:19:23 - This event loop is already running
Traceback (most recent call last):
  File "G:\projects\jerin\first-step\nenv\Lib\site-packages\chainlit\utils.py", line 44, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\projects\jerin\first-step\nenv\Lib\site-packages\chainlit\callbacks.py", line 118, in with_parent_id
    await func(message)

**Comment by pchalasani** [comment]
before trying out a chainlit example, does a basic cli example work with your vertex-ai configs?

**Comment by InfantJerin** [comment]
yes, it is working in cli

**Comment by InfantJerin** [comment]
![example ](https://github.com/user-attachments/assets/9d4d2cbf-aab2-4bd0-92c0-8e7b499df034)

attached the code, the log statement 'good' is getting printed multiple times.

**Comment by pchalasani** [comment]
does this chainlit example work for you with a simpler LLM setup, e.g. OpenAI or ollama/... ?

**Comment by InfantJerin** [comment]
after adding following snippet it worked. 
import nest_asyncio

nest_asyncio.apply()

**Comment by InfantJerin** [comment]
![chainlit 1 1 202](https://github.com/user-attachments/assets/4c51abdf-b1a3-4ba7-8100-9514cfbba4b1)
![new chainlit](https://github.com/user-attachments/assets/3cacb833-d81d-4e6e-b0b6-08b8b9e60208)
Also with recent update in chainlit, the output does not look good.

**Comment by pchalasani** [comment]
Note that in langroid we pin chainlit to a specific old version. 
We haven't tested with their new updates, and I'm not surprised that recent versions are not good.
