### ISSUE TITLE
Removing raw tool output from the messaging history: example / standard solution

### ISSUE THREAD

**Issue by Trel725** [langroid/langroid#605]
**Problem description**

When using tools for requesting additional data, it is frequently needed to make some preprocessing on raw tool output (e.g. selecting relevant information from the raw webpage). In this case the raw tool output is being stored in the message history and unnecessary loads context size of the model. That is exactly the case described in the FAQ for the RAG scenario (although it's even more general than just RAG), but no clear solution is offered. 
Both `_llm_response_temp_context` and  `llm_response_forget` are a bit cryptic and very low-level.  The perfect solution should be convenient to use with general langroid interface.

**Describe the solution you'd like**
One convenient option I can see would be `Task` argument like `store_raw_tool_output=True`. When set to False, raw tool output would be cleared from the message history. 
Probably even better would be to implement this feature as argument on the Tool level, since Agent can use multiple tools and some of the outputs might actually be necessary to store.

**Describe alternatives you've considered**
My first idea was to set `erase_substeps=True`, however this leads to difficult to predict behavior, as warned in the documentation. The temporary solution I've found (inspired by the an example in the source) is to override the  `llm_response` method of `ChatAgent`:

```python
class ForgettingAgent(ChatAgent):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._tool_used_in_last_step = False

    def llm_response(
        self,
        query: None | str | ChatDocument = None,
    ) -> Optional[ChatDocument]:
        """
        If we don't want to overload the context with raw responses from the tools,
        we need to perform a careful surgery on the message history to remove the tool output
        """
        n_msgs = len(self.message_history)
        response = super().llm_response(query)
        # if agent requested the tool, we keep the response as it will be necessary in the next step
        if "TOOL:" in response.content:
            self._tool_used_in_last_step = True
            return response
        # If agent did not request the tool, i.e. tool was used in the previous step
        # we remove the tool output from the message history (second last message)
        else:
            self._tool_used_in_last_step = False
            self.message_history.pop(-2) if len(self.message_history) > n_msgs else None
        return response
```
This solution works, but its neither convenient nor elegant. A standardized solution or at least an example in documentation would be very helpful.

**Additional context**
Thanks a lot for the langroid! The idea behind it is truly great, it balances so nicely between being conceptually simple while powerful.

**Comment by pchalasani** [comment]
Thanks @Trel725 , glad you like langroid!

Making sure I understand what you're looking for:
- [1] LLM generates tool msg, e.g. `get_web_page_content_tool`
- [2] `agent_response` (i.e. tool handler) gets raw data `R` from web page, then applies `preprocess(D)` to produce a concise version `C`, and the `agent_response` returns `C`
- [3] LLM sees concise version `C` and responds, etc.

In this case only the concise `C` is kept in `message_history`, and there's no bloat issue. 

But I think you meant the following scenario:
- [1] LLM generates tool msg, e.g. `get_web_page_content_tool`
- [2] `agent_response` (i.e. tool handler) gets raw data `R` from web page, then **returns** `R` 
- [3] LLM sees `R` and extracts relevant parts `C`, and proceeds

In this case yes `R` is kept in conv history, whereas only `C` is relevant for future conversation.

Is the second scenario what you hand in mind?

**Comment by Trel725** [comment]
Hey, sorry for not being specific enough, I indeed meant scenario 2. You are right that my problem can be reduced to case 1, if `preprocess(D)` is a standalone call to LLM, and that was my another idea to solve this problem. However, again, that wouldn't be particularly elegant solution, so having native support would be great.

By the way, does langroid allow simple stateless LLM calls from tools (e.g. is it possible to access LLM instance inside `Agent` from the tool? Of course, that's easy to achieve by directly calling LLM API, but maybe there's more native ways to do it?

**Comment by pchalasani** [comment]
> does langroid allow simple stateless LLM calls from tools (e.g. is it possible to access LLM instance inside `Agent` from the tool?

I think you're looking to be able to define something like `handle` within a `ToolMessage` subclass defn, but have access to the agent's llm -- yes there is a way to define such a method within a Tool: it's called `response`, see an example in this test:

https://github.com/langroid/langroid/blob/main/tests/main/test_tool_messages.py#L810

For your scenario of using the LLM to preprocess the large raw result R into a concise C, you could 
do something like:

```python
def response(self, agent: MyAgent) -> Any:
    #self.raw_result would contain the large raw result
    msg_hist = [ 
        LLMMessage(content = "You are expert at extracting...", role = Role.SYSTEM),
        LLMMessage(content=f"extract the relevant parts from {self.raw_result}")
    ]
    result =  agent.llm.chat(msg_hist)
    return result.content # now content is concise 
```

This uses the agent's LLM to do a one-off task with a fresh system msg, not polluted by any priori history.
Since we're not gaining any special advantage by using the agent's LLM,
it's even simpler to just directly create an llm instance the usual way (as in `test_llm.py`),
and send the above msg pair to it.

Another way would be to define an `ExtractorAgent`, which will have its own separate msg history,
and invoke that from the `handle` method of this Tool. 

And so on. There are many possible ways to do this. But I'll think of a canonical example to add to docs, or a langroid-native mechanism. You brought up a good point.

**Comment by pchalasani** [comment]
@Trel725 turns out it was easy to implement, see the PR #606 
And this [test](https://github.com/langroid/langroid/pull/606/files#diff-75a57d2e6f1b2c2d3b066069732bc8aa4229d9d2d571f0a99419e70d489a5467R1186)

**Comment by pchalasani** [comment]
See release 0.22.0, docs here: https://langroid.github.io/langroid/notes/large-tool-results/

**Comment by Trel725** [comment]
Wonderful, thank you very much! Just tried it and it works perfectly. I will close the issue.
