### ISSUE TITLE
Custom tool handler method

### ISSUE THREAD

**Issue by alexagr** [langroid/langroid#627]
**Is your feature request related to a problem? Please describe.**

Langroid currently assumes that tool handlers are class methods with names identical to tool's name (`request` attribute).
This is somewhat unsafe - as tool name may be identical to an existing method of Agent class.
Also for use-cases where tools are defined dynamically (e.g. based on some "configuration data" stored in external database) this requires creation of multiple dynamic methods in Agent object - which may be a challenge for garbage collection.

**Describe the solution you'd like**
Add a new optional "handler" attribute to `ToolMessage`:
```
class ToolMessage(ABC, BaseModel):
    ...
    handler: Optional[str] = None
```

When the `handler` attribute is not `None`, use it to find the handler method instead of default `request` attribute value.

The signature of the `handler` method will be as follows:
```
def handler(self, msg: ToolMessage, request: str)
```
Use of `request` parameter (name of the tool) will allow creation of a single "tool handler" for multiple tools.

**Describe alternatives you've considered**
I initially thought about simply adding "tool_" prefix to the default tool handler - but this is a "breaking change" and thus IMO not a good idea.

**Comment by pchalasani** [comment]
@alexagr thanks for this suggestion. 

Suppose we have

```python
class MyTool(ToolMessage):
    request: str = "my_tool"
    handler: str|None = "my_handler"
```

Are you saying in this case we would handle this by runing `agent.my_handler(msg: MyTool, request="my_tool")` ?

If that's not what you had in mind can you create the right sample code?

**Comment by alexagr** [comment]
@pchalasani yes, exactly
