### ISSUE TITLE
chore: update docstring-parser version to 0.16

### ISSUE THREAD

**Issue by christiankyle-ching** [langroid/langroid#629]
**Is your feature request related to a problem? Please describe.**
Most recent version of [docstring-parser](https://github.com/rr-/docstring_parser/releases/tag/0.16) is 0.16. Other libraries use this `^0.16`, and it conflicts with `langroid` forcing downgraded version to be used.

**Describe the solution you'd like**
Update `docstring-parser` dependency to `^0.16`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pchalasani** [comment]
Thanks for raising this @christiankyle-ching  - fixed in v0.31.2
