### ISSUE TITLE
fix failing test_async_handlers.py

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#640]
The `test_async_tool_handler` occasionally fails on gh actions as follows. 
```
=========================== short test summary info ============================
FAILED tests/main/test_async_handlers.py::test_async_tool_handler[True] - assert 4 == 1
 +  where 4 = len([ChatDocument(content='{"handler": "async", "seconds": 0.3, "end": 6867.515397916}', metadata=ChatDocMetaData(source='...l_id2result=None, oai_tool_choice='auto', function_call=None, tool_messages=[], all_tool_messages=[], attachment=None)])
FAILED tests/main/test_async_handlers.py::test_async_user_response_batch[True] - AssertionError: assert 2 == 1
 +  where 2 = len([ChatDocument(content='async response 1', metadata=ChatDocMetaData(source='User', is_chunk=False, id='9c8eda42-d0f9-4c...l_id2result=None, oai_tool_choice='auto', function_call=None, tool_messages=[], all_tool_messages=[], attachment=None)])
```

@nilspalumbo  Could it be because the sleep time is too short? I've increased the sleep times to 1,2,3,4 instead of 0.1, 0.2, 0.3, 0.4

**Comment by nilspalumbo** [comment]
That's odd; even with the shorter sleep times this passed locally every time over 100 trials. I did see a failure when I reduced the times to 0.01, 0.02, etc., so maybe this is down to the test runners being slower than my local machine.

**Comment by nilspalumbo** [comment]
Does it still fail with 1,2,3,4?

**Comment by nilspalumbo** [comment]
We could make this more reliable by having the responders wait until all previous responders are done with the downside being that this would become an infinite loop when the test should fail (where the async handlers are blocking). The timeout would catch this though; does this seem like a good solution?

**Comment by pchalasani** [comment]
Not sure what is going on in this specific test, but for general use, I added some fixtures in `conftest.py` to fallback to other models, e.g. `gemini-2.0-flash`. Example is in `test_recipient_tool`

See PR https://github.com/langroid/langroid/pull/641

**Comment by pchalasani** [comment]
> The timeout would catch this though; does this seem like a good solution?

ok, let's try this after my PR #641 passes
