### ISSUE TITLE
Confusing tool instructions when using OpenAI functions / tools APIs

### ISSUE THREAD

**Issue by alexagr** [langroid/langroid#649]
**Describe the bug**
`ToolMessage` class has `instructions` method that adds the following text to System Prompt:

```
IMPORTANT: When using this or any other tool/function, you MUST include a 
`request` field and set it equal to the FUNCTION/TOOL NAME you intend to use.
```

However when working with OpenAI models and `use_functions_api = true` (default) the function definition actually lacks the `request` parameter:
```
   'functions': [
        {
            'name': 'cancel_tool',
            'description': '\n    Cancel appointment for a caller with a given <patient_name> and <ssn>\n    with <doctor> 
on <date>\n    ',
            'parameters': {
                'type': 'object',
                'properties': {
                    'patient_name': {'type': 'string'},
                    'ssn': {'type': 'string'},
                    'doctor': {'type': 'string'},
                    'date': {'type': 'string'}
                },
                'required': ['date', 'doctor', 'patient_name', 'ssn']
            }
        }
    ],
```

The LLM still seems to obey the instructions and adds `request` parameter to function calls:
```
[Entity.LLM]Entity.LLM[] FUNC[cancel_tool]: FUNC: {
  "name": "cancel_tool",
  "arguments": {
    "patient_name": "Joe",
    "ssn": "123456",
    "doctor": "Josef Katz",
    "date": "tomorrow at 6pm",
    "request": "cancel_tool"
  }
}
```
But this looks messy and increases the System Prompt length for no apparent reason.

**Suggested fix**

Add support for new `use_tools_instructions` method in ToolMessage class that defines instructions that should be used (added to system prompt) ONLY when `use_tools == True`. Rename the current `ToolMessage.instructions` to `ToolMessage.use_tools_instructions`.

**Comment by pchalasani** [comment]
fixed in #652
